### ISSUE TITLE
Typescript ES6 has problems with syntax

### ISSUE THREAD

**Issue by floflock** [cyrilwanner/next-optimized-images#103]
If I want to import an image via ES6 `import` in a TypeScript file, the module cannot be found, because of missing declaration:
![image](https://user-images.githubusercontent.com/3831745/63653284-f907a780-c76a-11e9-958a-a8282149bd0c.png)

I do declare the modules here:
![image](https://user-images.githubusercontent.com/3831745/63653299-2ce2cd00-c76b-11e9-9834-568bb4047d66.png)

But because of the query parameters, it does not work. Are there any other possibilities to give the query information to the responsive-loader?

I can use `require`, but it hat more consistency if I use `import` everywhere.
I can use the default configuration, but I cannot gather a specific image size then, srcSet does work then.

Is there any solution for TypeScript?

**Comment by cyrilwanner** [comment]
Hi @floflock 
You can add more `declare module` statements for the query parameters:
```ts
declare module '*.jpg?resize';
```

If you want to add every possible combination, this could get quite huge.. I'll try to implement this in this package and ship those typings, but you can use this as a quickfix.

**Comment by tomaskallup** [comment]
@cyrilwanner Sadly that won't fix everything, if you combine multiple params eg. `?resize&sizes[]=500` you would need to add that to the definition 
```ts
declare module '*.jpg?resize&sizes[]=500';
```

Meaning you would need to add every single combination you use, because `*.jpg?*` doesn't seem to work.

**Comment by karl** [comment]
I worked around this by adding the following TypeScript declaration:

```ts
declare module '*&ts-ignore' {
  const value: string;
  export = value;
}
```

And then importing images as follows:

```
import thumbsUpImage from './thumbs-up.png?resize&size=408&ts-ignore';
```

**Comment by rootical** [comment]
@karl 's suggestion doesn't work for me. The images can't be found, only `require` works :(
