### ISSUE TITLE
How do you require the favicon?

### ISSUE THREAD

**Issue by semyou** [cyrilwanner/next-optimized-images#118]
Hi,

How do you recommend we require the favicon in the header. Right now we have an entry in the HEAD:
    <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico" />

**Comment by cyrilwanner** [comment]
If you are referring to `.ico` files, please read this section in the readme: https://github.com/cyrilwanner/next-optimized-images#handleimages (next to the ℹ️). After you have enabled those file, you can import them the same way as other images.

**Comment by semyou** [comment]
@cyrilwanner - will it work even if importing a favicon is done like this?
<link rel="icon" href="favicon.ico" type="image/x-icon" />

**Comment by cyrilwanner** [comment]
I think sharing the code didn't work, at least I can't see anything.

**Comment by semyou** [comment]
Now added the code brackets
