### ISSUE TITLE
not work in nextjs 9.3x + compose plugin

### ISSUE THREAD

**Issue by vincalkr** [cyrilwanner/next-optimized-images#150]
Hi
Using 

> module.exports = withPlugins([
>   [optimizedImages, { inlineImageLimit: -1 }],
>   nextImagesPlugin,
> ], nextEnvConfig)

image inner background and others result empty or corrupted
![image](https://user-images.githubusercontent.com/49186405/80090708-34f44600-8560-11ea-9c6a-bcf07d7741ac.png)

**Comment by cyrilwanner** [comment]
Hi @vincalkr 
This problem should now be resolved with version `v2.6.0` (just published a few minutes ago).
Can you please try it again? If you still have problems, feel free to open a new issue. Thanks!

**Comment by vincalkr** [comment]
Hi @cyrilwanner but still it not work.

here are some indications ..

![image](https://user-images.githubusercontent.com/49186405/80273794-a4d80d00-86d5-11ea-88f7-8de5e2076ced.png)

![image](https://user-images.githubusercontent.com/49186405/80273819-d650d880-86d5-11ea-92e0-2068fe829cc0.png)

![image](https://user-images.githubusercontent.com/49186405/80273825-f54f6a80-86d5-11ea-9388-a8df01328cc2.png)

thanks

**Comment by fcpauldiaz** [comment]
is there an update on this?

**Comment by vincalkr** [comment]
nothing

Il giorno dom 24 mag 2020 alle 23:09, Pablo Díaz 
<notifications@github.com> ha scritto:
