### ISSUE TITLE
Requiring images with dynamic paths

### ISSUE THREAD

**Issue by amytych** [cyrilwanner/next-optimized-images#16]
Is it possible to require images with dynamically created paths? E.g.:

```javascript
import React from 'react';

export default ({ imgName }) => (
  <div>
    <img src={require(`./images/${imgName}`)} />
  </div>
);
```

Something along the lines described in this article https://medium.com/@bogdan_plieshka/loading-static-and-dynamic-images-with-webpack-8a933e82cb1e

Thanks for any help!

**Comment by cyrilwanner** [comment]
Hi @amytych 

Yes, in my project, this code is working:
```javascript
import React from 'react';

export default () => (
  <div className={styles.Row}>
    {
      [1, 2, 3].map(imageId => (
        <img key={imageId} src={require(`./assets/images/dynamic/image-${imageId}.jpeg`)} />
      ))
    }
  </div>
);
```

I now even created the same component you posted, and it is working too for me.
Do you get any error during build or request?

**Comment by kotay** [comment]
This works great, how can I get this to work with query parameters (`?webp`), the following does not seem to work:
```

import React from 'react';

export default () => (
  <div className={styles.Row}>
    {
      [1, 2, 3].map(imageId => (
        <img key={imageId} src={require(`./assets/images/dynamic/image-${imageId}.png?webp`)} />
      ))
    }
  </div>
);
```

**Comment by aulneau** [comment]
I am also getting an issue importing images dynamically when appending the path with -> `?webp`

**Comment by cyrilwanner** [comment]
Unfortunately, I still haven't found a solution yet and I actually think this is a limitation or bug of webpack as other projects also have this problem and I couldn't find a working solution on the internet.
I currently have one idea left which I would want to try, but if this also won't work, I'll create an issue in the webpack repository to ask for help.
I'll keep you posted and sorry for the inconveniences.

**Comment by cyrilwanner** [comment]
And as a temporary solution (I know it is a bit verbose and not clean, I'll still try to find a solution to this issue), something like this should work in the meantime:

```javascript
const images = {
  id1: require('./assets/images/dynamic/image-id1.png?webp'),
  id2: require('./assets/images/dynamic/image-id2.png?webp'),
  id3: require('./assets/images/dynamic/image-id3.png?webp'),
  id4: require('./assets/images/dynamic/image-id4.png?webp'),
  // ...
};

export default () => (
  <div className={styles.Row}>
    {
      ['id1', 'id2', 'id3', 'id4'].map(imageId => (
        <img key={imageId} src={images[imageId]} />
      ))
    }
  </div>
);
```

**Comment by cyrilwanner** [comment]
Hello everyone and sorry for the late reply.
I found an undocumented parameter within [`require.context`](https://github.com/webpack/docs/wiki/context) which resolves our problem.

We can add resource queries to the first argument of `require.context` where the directory is specified.
The example @kotay posted would now look like this:

```js
import React from 'react';

const requireWebpImage = require.context('./assets/images/dynamic?webp', false, /\.png$/);

export default () => (
  <div className={styles.Row}>
    {
      [1, 2, 3].map(imageId => (
        <img key={imageId} src={requireWebpImage(`./image-${imageId}.png`)} />
      ))
    }
  </div>
);
```

You maybe have to change the parameters of `require.context` (see the [docs](https://github.com/webpack/docs/wiki/context)), but for me, it worked in my example project. Does this also work for your use-cases?

**Comment by jamesemwallis** [comment]
Ran in to this problem earlier. I was unable to use a totally dynamic path.

This didn't work: 
```
const sauce = '../../images/background.jpg';
<img src={require(`${sauce}`)} />
```

But this did work:
```
const sauce = 'background.jpg';
<img src={require(`../../images/${sauce}`)} />
```

**Comment by albertpeiro** [comment]
This works:
```
const Picture = ({ path, srcSizes, ...props }: PictureProps) => {
  return (
    <picture>
      {srcSizes &&
        srcSizes.map((size, index) => (
          <source
            key={index}
            media={`(max-width: ${size}`}
            srcSet={require(`~/images/${path}?&webp`)}
            type="image/webp"
          />
        ))}
      {/* 
      <source srcSet={require(`~/images/${path}`)} type="image/jpeg" /> */}
      <img src={require(`~/images/${path}?`)} {...props} />
    </picture>
  );
};
```

but using size param doesn't work (and it's installed and works otherwise outside the map):
```
<source
            key={index}
            media={`(max-width: ${size}`}
            srcSet={require(`~/images/${path}?size=${size}&webp`)}
            type="image/webp"
          />
```

**Comment by DenisOleksiuk** [comment]
In my case it was helps me
```
  const burgerIcon = isOpen ? (
    <img src={require('../../../public/close_black_24dp.svg')} />
  ) : (
    <img src={require('../../../public/menu_black_24dp.svg')} />
  );
```

**Comment by rjlg** [comment]
> Hello everyone and sorry for the late reply.
> I found an undocumented parameter within [`require.context`](https://github.com/webpack/docs/wiki/context) which resolves our problem.
> 
> We can add resource queries to the first argument of `require.context` where the directory is specified.
> The example @kotay posted would now look like this:
> 
> ```js
> import React from 'react';
> 
> const requireWebpImage = require.context('./assets/images/dynamic?webp', false, /\.png$/);
> 
> export default () => (
>   <div className={styles.Row}>
>     {
>       [1, 2, 3].map(imageId => (
>         <img key={imageId} src={requireWebpImage(`./image-${imageId}.png`)} />
>       ))
>     }
>   </div>
> );
> ```
> 
> You maybe have to change the parameters of `require.context` (see the [docs](https://github.com/webpack/docs/wiki/context)), but for me, it worked in my example project. Does this also work for your use-cases?

Thanks! This resolved my issue.
