### ISSUE TITLE
[Performance] Each Require() Increases Page JS Size

### ISSUE THREAD

**Issue by pxwee5** [cyrilwanner/next-optimized-images#165]
```
  const imgMobile = require(`@src/images/${filename}?size=768`);
  const imgTablet = require(`@src/images/${filename}?size=1280`);
  const imgDesktop = require(`@src/images/${filename}?size=1920`);
```
Each request here makes the page.js file increse by around 2KB - 3KB gzipped. Ouch :( 

Currently I'm using a `<picture>` source tag to show mobile, tablet and desktop background images. 
It is currently slower compared to if I'm only showing the desktop version of the image. Not much optimization according to Google Pagespeed.

Can we not include those unused images in the bundle?

**Comment by pxwee5** [comment]
Fixed this by shifting everything to `getStaticProps`. But it is still quite difficult to require images. We can't do stuff like 

```
const imgDesktop = require(`${path}?size=1920`);
```

**Comment by Nadav42** [comment]
small images are converted to base64 and inserted into your js bundle, you can add `inlineImageLimit: 0` in next.config.js to prevent this behaviour

**Comment by mauriciocarnieletto** [comment]
I'm having the same problem, i didn't get how do you solved it?

**Comment by pxwee5** [comment]
Just explained it above, with some drawbacks.
