### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by jonatanlins** [cyrilwanner/next-optimized-images#171]
Hi, I noticed that in `.tsx` files, images work nice when imported using the `require` syntax, but when you try to use the `import` syntax, an TypeScript error occurs.

```javascript
// it works
const myImage = require("./image.png")

// it fails
import myImage from "./image.png"
```

This can be easily fixed by adding an `index.d.ts` file with some type definitions to the root folder.

I'm working on this just now :)

**Comment by jonatanlins** [comment]
I just realized that this problem has been fixed in canary version, sorry for the inconvenience.

**Comment by adoidadox2** [comment]
> I just realized that this problem has been fixed in canary version, sorry for the inconvenience.

You should research a few more and make sure that there really is a problem, so that it does not occupy the developers, as happened here
