### ISSUE TITLE
Error: Cannot find module $path

### ISSUE THREAD

**Issue by dalanmiller** [cyrilwanner/next-optimized-images#185]
Having an issue I think with getting the plugin working as this is a valid file at `public/images/products/6607330/1.jpg`. I assume based on `assetConfig` which I haven't changed that the path I'm providing will be concatenated to `public`. 

Anything I can sanity check here? 

```
// next.config.js 
const withPlugins = require('next-compose-plugins');
const optimizedImages = require('next-optimized-images');

module.exports = withPlugins([
  optimizedImages,
]);
```

<img width="996" alt="Screen Shot 2020-08-05 at 11 07 05 pm" src="https://user-images.githubusercontent.com/863286/89416322-9e1d5500-d71c-11ea-86bb-2d27a6f6097c.png">

**Comment by Vincent-3DAT** [comment]
try `require('public/images/'+src)`
if that doesnt work try a filepath that is relative to _document

**Comment by dalanmiller** [comment]
> try require('public/images/'+src)

No good ;(

>  if that doesnt work try a filepath that is relative to _document

Tried the path relative to `_document` (`../public/images/products/1234/1.jpg`) but also still not working.

**Comment by cyrilwanner** [comment]
You need at least one static path before your variable in a `require` statement, this is a limitation of webpack: https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

Also, your path is relative to your current file. It works exactly the same as when you would import another js file.

**Comment by dalanmiller** [comment]
What a bizarre limitation! But makes sense that the less specific you are, the more files WebPack will need to load to ensure that your file will be available to import.

 I've modified this so that the `require(` has the static path up front and then the prop I pass in is just the folder name and filename in the path. However, it still seems to be failing for the same reasons. Unclear why the error isn't showing the full path and instead just the latter part? 

e.g. `src = '6450868/1.jpg'`

<img width="991" alt="Screen Shot 2020-08-06 at 8 53 53 am" src="https://user-images.githubusercontent.com/863286/89471795-94244200-d76e-11ea-8c16-a080b2b9c375.png">

Side note: Is there a manual or different way to trigger image optimization other than using `require`? 

edit:

```
const webpImage = require(`../public/images/products/${src}?webp`)
```

Also fails.

**Comment by dalanmiller** [comment]
Same as #16

**Comment by dalanmiller** [comment]
Issue here was jpg files with capitalised extensions and not lowercase 🤦‍♂
