### ISSUE TITLE
[canary] webp settings has no effect

### ISSUE THREAD

**Issue by tam315** [cyrilwanner/next-optimized-images#202]
Hi, thanks for a great library!

I'm testing canary build now, I noticed that webp options has no effect.
(I want more lower quality webp images)
My setting is as follows.
Am I missing something?
```js
module.exports = withPlugins([
  [
    optimizedImages,
    {
      images: {
        webp: {
          quality: 10,
        },
      },
    },
  ],
]);
```

**Comment by evgenyboxer** [comment]
@cyrilwanner any update on this? I'm doing the same for "svgo" (trying to disable a plugin), and it has no effect.

**Comment by 0x5am5** [comment]
Damn, I've just came across this issue. Glad I'm not the only one!

**Comment by Cr0WD** [comment]
@cyrilwanner Can you please fix it ??
