### ISSUE TITLE
Huge size when using the package?

### ISSUE THREAD

**Issue by melvin2016** [cyrilwanner/next-optimized-images#214]
I have a component called **ImageLoaderUtil** which I'm using to convert raw images to webp and also place lqip placeholders. But I get huge page sizes when Next.js builds the site.

### **ImageLoaderUtil.jsx** Component
<img width="642" alt="Screenshot 2020-10-17 at 3 19 32 PM" src="https://user-images.githubusercontent.com/22199666/96334307-59ebf080-108d-11eb-8d01-8b7654b6cb30.png">

### Size of the Page with **webp and lqip loaders**  when Next.js builds the site.
<img width="1121" alt="Screenshot 2020-10-17 at 3 20 01 PM" src="https://user-images.githubusercontent.com/22199666/96334316-6ff9b100-108d-11eb-8241-c992ae882a30.png">

### Size of the Page when I removed **webp and lqip loaders** 

<img width="1121" alt="Screenshot 2020-10-17 at 3 21 38 PM" src="https://user-images.githubusercontent.com/22199666/96334318-7425ce80-108d-11eb-867f-90ba237df3a0.png">

Can someone suggest to me a better solution? 🙂

**Comment by z0lo13** [comment]
try loading images dynamically without ssr it will remove images from build
