### ISSUE TITLE
Question: Does it support image optimization from external URL (images that are not in our project folder)?

### ISSUE THREAD

**Issue by agustinusnathaniel** [cyrilwanner/next-optimized-images#224]
I don't see in the README that says this package doesn't optimized image from external URL and I also tried it myself that it didn't work. But I just wanna make sure.

If this doesn't optimize image from external source, please confirm and add it (or maybe I'll make a PR to add the statement) to the readme to state that this package doesn't optimize image from external source. Thank you.

**Comment by philmetzger** [comment]
Also I would like to know this.

Currently I get this message when i try it:

`Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.`

`<Img src="https://img.freepik.com/free-vector/color-wing-transparent-set_1284-8933.jpg" />`

**Comment by madzadev** [comment]
@sozonome @philmetzger

> It is a planned feature but not yet included in the canary version. But I'll definitely include that feature. I'll inform you once the feature can be tested in the canary version.

_Originally posted on Jul 25, 2020 by @cyrilwanner in https://github.com/cyrilwanner/next-optimized-images/issues/166#issuecomment-663852222_

**Comment by ShahriarKh** [comment]
Any updates on this?
This one is really critical.

**Comment by Pipe-Runner** [comment]
Wow, this turned out to be a deal-breaker for me as most of my images in my portfolio are drawn out from Github raw content. Seems like I would not be able to use this after all.
