### ISSUE TITLE
Now deploy error

### ISSUE THREAD

**Issue by yasaricli** [cyrilwanner/next-optimized-images#26]
Hello. I get this error when I deploy.

    now

'(server) ./static/images/google-plus-icon.svg\nModule build failed: TypeError: csstree.translate is not a function\n

next.config.js

```
const withSass = require('@zeit/next-sass')
const withImages = require('next-images');
const withOptimizedImages = require('next-optimized-images');
module.exports = withSass(withOptimizedImages());
```

**Comment by cyrilwanner** [comment]
Hi @yasaricli 

I tried to reproduce this error with the same next.config.js and a sample svg image but it worked without any problem for me.
Can you provide me more details about the error?
* Is this your whole next.config.js or just a part of it?
* How do you include the svg file in your project?
* As I see `csstree.translate` in the error, do you have a special sass/css setup?
Or maybe you can even provide me a minimalistic repository to reproduce this error.
