### ISSUE TITLE
TypeError: unsupported file type: undefined (file: undefined)

### ISSUE THREAD

**Issue by Jaydeep189** [cyrilwanner/next-optimized-images#284]
error - ./public/logo/amc.png
TypeError: unsupported file type: undefined (file: undefined) 

This is my next.config.js

I am using imagemin-optipng for optimization

I am building a static site with nextjs

```const withOptimizedImages = require("next-optimized-images");

const nextConfig = withOptimizedImages({
  optimizeImagesInDev: true,
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    images: {
      unoptimized: true,
    },
  },
});
module.exports = nextConfig;

**Comment by signorbusi** [comment]
I'm facing exactly the same problem

**Comment by abbasEbadian** [comment]
I used the `withPlugins` version of `.next.config` file and set `handleImages: ['*']` then the error gone.

**Comment by hannah26hannah** [comment]
I also encounted this error. I'm using `withPlugins` as well, and for the default config, I set `disableStaticImages` inside `images`  as true and luckily it resolved this error.

```js
const nextConfig = {
...
  images : {
    disableStaticImages: true,
  }
...
}
```

**Comment by CallumJHays** [comment]
I updated from next@10 to next@12 and ran into this. @abbasEbadian 's fix did silence the error but broke all images.

@hannah26hannah 's fix on the other-hand worked. Cheers!

**Comment by Jaydeep189** [comment]
> ```js
> disableStaticImages: true,
> ```

It worked! 
Thanks
