### ISSUE TITLE
img-loader as peer dependency

### ISSUE THREAD

**Issue by mxs** [cyrilwanner/next-optimized-images#37]
Hi there,

When I use a a custom webpack config with Next.js I need to also img-loader for this plugin to work. This would mean that in node_modules there is img-load at the root and also inside node_modules of next-optimized-images.

It feels like having img-loader as a peer dependency of next-optimized makes sense?

**Comment by cyrilwanner** [comment]
Hi @mxs

Are you using version 1 or 2 of img-loader?

If you are using version 2: this plugin is not yet compatible with it, so there have to be two versions installed. However, I'm currently working on an update to v2.

If you are using version 1: This is actually something which NPM already takes care of (at least newer versions, it was different with v2.x or older I think).
E.g. when you execute `ls -la node_modules/next-optimized-image` you should not see another node_modules folder in it. NPM installs the dependencies of this (and other) plugins in the same level as all the other ones.

**Comment by mxs** [comment]
Yes we are using version 3 of the img-loader.

Thank for the response and keep up the good work!
