### ISSUE TITLE
Adding ?sprite to the module doesn't work

### ISSUE THREAD

**Issue by ahmadalfy** [cyrilwanner/next-optimized-images#38]
Hello,

My ESLint is complaining when I try to import a file as an svg sprite as follow:

```
import idea from '../static/images/icons/idea.svg?sprite';
```

I added comments to ignore the error and it worked. When I tried to test the component with jest it failed to import the file.

**Comment by cyrilwanner** [comment]
Hi @ahmadalfy 
	
This probably comes from jest not knowing our webpack config (where we define these resource queries). I just googled a bit and there are still open issues and pull requests for jest to solve this issue (looks like a lot of devs have this problem).
I didn't try it out, but some people are having success with this config option to simply ignore all required images: https://jestjs.io/docs/en/configuration#modulepathignorepatterns-array-string
There are probably also other settings which could help you.

**Comment by ahmadalfy** [comment]
@cyrilwanner Thank you, closing it as it is not related here and will check your suggestion and update you. Thanks again
