### ISSUE TITLE
Compatible with "next export"?

### ISSUE THREAD

**Issue by Vadorequest** [cyrilwanner/next-optimized-images#53]
I wonder if this plugin applies when exporting using `next export` command, which generates a static build. I believe it should since all the operations are doing at the webpack level (AFAIK), but I could be wrong.

**Comment by cyrilwanner** [comment]
Yes, it works exactly the way you wrote it. All images will also be optimized during a `next export`. If you don't want that, you can exclude the plugin from the export phase in your next.config.js file.

Please feel free to open another ticket if you are experiencing problems with `next export` or any other feature of this plugin.
