### ISSUE TITLE
Unable to get query params to work with Jest

### ISSUE THREAD

**Issue by joebanks10** [cyrilwanner/next-optimized-images#57]
Hello, I'm having trouble getting imports w/ query params to work in a Jest environment. I set up an example project here:

https://github.com/joebanks10/jest-next-optimized-images 

Is there something I need to add to get it to work?

**Comment by joebanks10** [comment]
I was able to get images to work by mocking them in the tests. In `jest.config.js`:

```
module.exports = {
  testPathIgnorePatterns: ['<rootDir>/.next/', '<rootDir>/node_modules/'],
  moduleNameMapper: {
    '^.+\\.(gif|png|jpg|ttf|eot)\\?(resize|sizes)(.+)?$':
      '<rootDir>/__mocks__/fileResizeMock.js',
    '^.+\\.(gif|png|jpg|ttf|eot)(\\?.+)?$': '<rootDir>/__mocks__/fileMock.js',
    '^.+\\.svg\\?(sprite|include)(.+)?$': '<rootDir>/__mocks__/svgMock.js',
  },
}
```

Full example can be found in the repo: https://github.com/joebanks10/jest-next-optimized-images

**Comment by makarov-foot** [comment]
joebanks10's repo now throws

> Cannot find module '../static/cart.svg?sprite' from 'index.js'

- it can't resolve name because of query prefix.

Somebody knows how to fix this?

**Comment by cyrilwanner** [comment]
Hi @makarov-foot 
I just checked out his repository and it is working for me without any error. I only run `npm install` and `npm test` and all tests are passing.

Are you sure that you didn't modify his `jest.config.js` file? Or did you configure jest in a special way or did any other modification to his project?
