### ISSUE TITLE
Add `?original` query param

### ISSUE THREAD

**Issue by cyrilwanner** [cyrilwanner/next-optimized-images#6]
If this query param is specified, a single image should not get optimized.

**Comment by notatestuser** [comment]
Could we also have a param to force use of the full URL (no inline)?

**Comment by cyrilwanner** [comment]
Sure, that's a good idea :) I'll add it with the next update (probably tomorrow).

**Comment by cyrilwanner** [comment]
It took a few more days, but the [`?original`](https://github.com/cyrilwanner/next-optimized-images#original) and [`?url`](https://github.com/cyrilwanner/next-optimized-images#url) (to force an image url) query parameters are now available with version 1.4.0 of `next-optimized-images` which just got published to npm.
Please don't hesitate to create a new issue if something is not working for you or if you have another idea for an improvement :)
