### ISSUE TITLE
Add SVG placeholder support

### ISSUE THREAD

**Issue by fandy** [cyrilwanner/next-optimized-images#65]
It would be really neat to add https://github.com/EmilTholin/image-trace-loader an option for `next-optimized-images`. The benefit of that vs LQIP is more visual detail without sacrificing file size.

**Comment by cyrilwanner** [comment]
This looks really cool! I didn't know this technique, I'll definitely try to add an option for this

**Comment by cyrilwanner** [comment]
I just had to try this out and published `v2.4.0` which supports this feature with the [`?trace`](https://github.com/cyrilwanner/next-optimized-images#trace) resource query. Thank you for the idea, I really like this one :)
