### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by Annihil** [cyrilwanner/next-optimized-images#66]
How could one makes this plugin work with stylus url()?
It is being ignored.

**Comment by cyrilwanner** [comment]
This plugin only supports styling solutions which use webpack for resolving `url(..)` calls. I've never used stylus, but unfortunately, it looks like they don't use webpack and implemented something on their own. I'll have to check if it is possible to hook into their url resolution. Or do you already know if this is possible and how?

**Comment by Annihil** [comment]
My bad it's totally picked by your plugin 👍
