### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by ryandeussing** [cyrilwanner/next-optimized-images#67]
it would be very helpful to have a demo project to see how this all works in the wild

**Comment by cyrilwanner** [comment]
Hi @ryandeussing 	
I just added the project which I always use to verify all features before an update (in the [examples/](https://github.com/cyrilwanner/next-optimized-images/tree/master/example) folder). It showcases all possible features, but might be a bit complex (it also shows expected image size of the original and compressed images and if it was correct etc).. Do you think I should better add a smaller and easier example project?

**Comment by TommySorensen** [comment]
@cyrilwanner A smaller and easier example would be perfect.

**Comment by cyrilwanner** [comment]
I added a smaller example to this repo, so I'll also close this issue. If you would like an example for a specific feature, feel free to create a new issue or even directly a PR with the example.
