### ISSUE TITLE
Can we optimise image url in scss file without cssModules?

### ISSUE THREAD

**Issue by Ktchan825** [cyrilwanner/next-optimized-images#70]
I am not familiar with cssModules, Why is it necessary to have cssModules to bundle the image url in css file?

**Comment by cyrilwanner** [comment]
Hi @Ktchan825 
If you are using `@zeit/next-sass`, it also works without css modules for me. Are you getting an error when running the dev server or build?

**Comment by Ktchan825** [comment]
Thanks for the reply
i am using `@zeit/next-sass`, it works after i changed `/static/xxx.png` to `../../static/xxx.png`

**Comment by cyrilwanner** [comment]
Glad to hear it is working 👍 Yes, we need to use relative imports, otherwise webpack can't resolve it correctly and will end up in an error.
