### ISSUE TITLE
Requiring image in server app

### ISSUE THREAD

**Issue by joebanks10** [cyrilwanner/next-optimized-images#77]
Is it possible to import/require an image in a server-side app? For instance, can you have `require('static/myimg.jpg') in `server.js` in this example: https://github.com/zeit/next.js/tree/canary/examples/custom-server-express 

I'm specifically trying to import an image in an api endpoint and send the image data to my client-side app.

**Comment by joebanks10** [comment]
Pushed an example repo here: https://github.com/joebanks10/next-optimized-images-express

**Comment by cyrilwanner** [comment]
This plugin is based on different webpack loaders. So, if you also build your server with webpack, it could work. But by default or when following the example you have linked, this is not the case and Next.js doesn't support building the server with webpack out of the box. So you would have to do that manually.

Another solution would be that you optimize the images with [`imagemin`](https://github.com/imagemin/imagemin) or another package on the server (the loader which this plugin uses also use imagemin). This would work without webpack, but maybe needs a few other adjustments.
