### ISSUE TITLE
Sprite generation is not unique

### ISSUE THREAD

**Issue by dimensi** [cyrilwanner/next-optimized-images#83]
I have 2 icons with the same name but in different folders.
The first icon is: `src/components/Footer/fb.svg`.
The second icon is: `src/componentsForContacts/ListOfContacts/fb.svg`.
These are different design icons.
But they generate the same id in both cases `fb--sprite`. Because of this, only one icon is displayed.

**Comment by cyrilwanner** [comment]
Hi @dimensi 	
It is possible to provide your own function or string which gets used to create the sprite id. You can read more about it here: https://github.com/kisenka/svg-sprite-loader#symbolid-string--functionpath-query-default-name (we just use the `svg-sprite-loader` internally so you can also use all of its configuration possibilities).
You can then set it in the [`svgSpriteLoader`](https://github.com/cyrilwanner/next-optimized-images#svgspriteloader) key in the options of next-optimized-images.

For example something like this (which appends the unique content hash to the sprite name):
```js
// next.config.js
const withOptimizedImages = require('next-optimized-images');

module.exports = withOptimizedImages({
  svgSpriteLoader: {
    symbolId: '[name]-[hash]'
  }
});
```

**Comment by cyrilwanner** [comment]
The default id has now changed with the newest version and they are now unique.

**Comment by VimLeSai** [comment]
Hi, i'm getting same hash after every build in image, please let me know if i'm missing or doing something wrong.

```JS
...
const withOptimizedImages = require('next-optimized-images');
...

...
 config.module.rules.push({
    test: /\.(jpg|jpeg|gif|png)$/,
    use: [
      {
        loader: 'url-loader',
        options: {
          esModule: true,
          limit: 2048,
          fallback: 'file-loader',
          publicPath: '/_next/static/images/',
          outputPath: 'static/images/',
          name: '[name]-[hash].[ext]',
        },
      },
    ],
...

module.exports = withNextEnv(withPlugins([[withOptimizedImages, ImgOptions], [StyleOptions]], {}));



```
