### ISSUE TITLE
Image marked as progressive loading like baseline

### ISSUE THREAD

**Issue by walmink** [cyrilwanner/next-optimized-images#99]
As the documentation says, image formats that support progressive images have this applied by default when optimizing.

I can see that the optimized images have the "Progressive" flag set to 1:
![image](https://user-images.githubusercontent.com/753479/61888073-24e10480-af03-11e9-85cf-9c1653322adb.png)

However, when I open the built site in Chrome, using dev tools to slow down the connection, I can see the images are loading in a baseline fashion.

What am I missing? How do I make the images load progressively, with a low-res version to start with?

**Comment by cyrilwanner** [comment]
Are you sure you tested this against a production build and not a development build? If yes, which image format has this issue? Have you used some additional query parameters?
